language: java
sudo: false # faster builds
jdk:
  - oraclejdk8
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true